<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This is the best we can do for now.  Currently the TextMate PHP bundle doesn't support extending things like 'support.function' or 'support.class' without cloning the entire grammar.  For now this will allow us to support the PHP and HTML grammars while maintaining a custom scope name.</string>
	<key>fileTypes</key>
	<array>
		<string>php</string>
		<string>tpl</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;!DOCTYPE|&lt;(?i:html)|&lt;\?(?i:php)</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--\s*&gt;)
		|^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$
		|&lt;\?(?:php)?.*\b(if|for(each)?|while)\b.+:
		|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)&gt;
		|^(?!.*?&lt;!--).*?--\s*&gt;
		|^&lt;!--\ end\ tminclude\ --&gt;$
		|&lt;\?(?:php)?.*\bend(if|for(each)?|while)\b
		|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)
		|^[^{]*\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>PHP (Breeze)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.php.breeze</string>
	<key>uuid</key>
	<string>38981A36-11CC-4307-8D87-84318F0B5CE4</string>
</dict>
</plist>
